# Generated by Django 5.2.10 on 2026-01-11 08:46

import apps.files.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='İzin verilen formatlar: DOC, DOCX, PDF, JPG, PNG, TIFF, XLS, XLSX', upload_to=apps.files.models.manuscript_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'jpg', 'jpeg', 'png', 'tiff', 'tif', 'xlsx', 'xls'])], verbose_name='Dosya')),
                ('file_type', models.CharField(choices=[('main_text', 'Ana Metin'), ('cover_letter', 'Kapak Mektubu'), ('title_page', 'Başlık Sayfası'), ('abstract', 'Özet'), ('tables', 'Tablolar'), ('figures', 'Şekiller'), ('supplementary', 'Ek Dosyalar'), ('ethics_approval', 'Etik Onay Belgesi'), ('copyright', 'Telif Hakkı Formu'), ('revision', 'Revizyon Dosyası'), ('revision_notes', 'Revizyon Açıklamaları'), ('other', 'Diğer')], db_index=True, default='other', help_text='Dosyanın türü', max_length=30, verbose_name='Dosya Türü')),
                ('original_filename', models.CharField(help_text='Yüklenen dosyanın orijinal adı', max_length=255, verbose_name='Orijinal Dosya Adı')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Dosya boyutu (byte)', verbose_name='Dosya Boyutu')),
                ('mime_type', models.CharField(blank=True, help_text='Dosyanın MIME tipi', max_length=100, verbose_name='MIME Tipi')),
                ('description', models.CharField(blank=True, help_text='Dosya hakkında kısa açıklama', max_length=500, verbose_name='Açıklama')),
                ('caption', models.TextField(blank=True, help_text='Şekil/tablo altyazısı', verbose_name='Altyazı')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Dosyaların görüntülenme sırası', verbose_name='Sıra')),
                ('revision_number', models.PositiveSmallIntegerField(default=0, help_text='Bu dosya hangi revizyona ait', verbose_name='Revizyon Numarası')),
                ('is_active', models.BooleanField(default=True, help_text='Dosya aktif mi? (Silinen dosyalar için False)', verbose_name='Aktif')),
                ('is_primary', models.BooleanField(default=False, help_text='Bu türdeki birincil dosya mı?', verbose_name='Birincil')),
                ('checksum', models.CharField(blank=True, help_text="SHA-256 dosya checksum'u", max_length=64, verbose_name='Checksum')),
                ('virus_scanned', models.BooleanField(default=False, help_text='Dosya virüs taramasından geçti mi?', verbose_name='Virüs Tarandı')),
                ('virus_scan_date', models.DateTimeField(blank=True, null=True, verbose_name='Virüs Tarama Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('replaces', models.ForeignKey(blank=True, help_text='Bu dosyanın yerine geçtiği önceki dosya', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='files.manuscriptfile', verbose_name='Değiştirdiği Dosya')),
                ('submission', models.ForeignKey(blank=True, help_text='Bu dosyanın ait olduğu gönderim', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submission', verbose_name='Gönderim')),
                ('uploaded_by', models.ForeignKey(help_text='Dosyayı yükleyen kullanıcı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Makale Dosyası',
                'verbose_name_plural': 'Makale Dosyaları',
                'ordering': ['file_type', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İndirme Tarihi')),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İndiren')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='files.manuscriptfile', verbose_name='Dosya')),
            ],
            options={
                'verbose_name': 'İndirme Logu',
                'verbose_name_plural': 'İndirme Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='manuscriptfile',
            index=models.Index(fields=['submission', 'file_type'], name='files_manus_submiss_382e75_idx'),
        ),
        migrations.AddIndex(
            model_name='manuscriptfile',
            index=models.Index(fields=['uploaded_by'], name='files_manus_uploade_ea2a86_idx'),
        ),
        migrations.AddIndex(
            model_name='manuscriptfile',
            index=models.Index(fields=['is_active'], name='files_manus_is_acti_b92bb5_idx'),
        ),
    ]
