# Generated by Django 5.2.10 on 2026-01-11 08:55

import apps.files.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('submissions', '0002_alter_author_options_alter_submission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filedownloadlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Download Log', 'verbose_name_plural': 'Download Logs'},
        ),
        migrations.AlterModelOptions(
            name='manuscriptfile',
            options={'ordering': ['file_type', 'order', 'created_at'], 'verbose_name': 'Manuscript File', 'verbose_name_plural': 'Manuscript Files'},
        ),
        migrations.AlterField(
            model_name='filedownloadlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Downloaded At'),
        ),
        migrations.AlterField(
            model_name='filedownloadlog',
            name='downloaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Downloaded By'),
        ),
        migrations.AlterField(
            model_name='filedownloadlog',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='files.manuscriptfile', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='filedownloadlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='caption',
            field=models.TextField(blank=True, help_text='Figure/table caption', verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 file checksum', max_length=64, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of the file', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='file',
            field=models.FileField(help_text='Allowed formats: DOC, DOCX, PDF, JPG, PNG, TIFF, XLS, XLSX', upload_to=apps.files.models.manuscript_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'jpg', 'jpeg', 'png', 'tiff', 'tif', 'xlsx', 'xls'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes', verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='file_type',
            field=models.CharField(choices=[('main_text', 'Main Text'), ('cover_letter', 'Cover Letter'), ('title_page', 'Title Page'), ('abstract', 'Abstract'), ('tables', 'Tables'), ('figures', 'Figures'), ('supplementary', 'Supplementary Files'), ('ethics_approval', 'Ethics Approval Document'), ('copyright', 'Copyright Form'), ('revision', 'Revision File'), ('revision_notes', 'Revision Notes'), ('other', 'Other')], db_index=True, default='other', help_text='Type of the file', max_length=30, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the file active? (False for deleted files)', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Is this the primary file of its type?', verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='mime_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100, verbose_name='MIME Type'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order of the files', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='original_filename',
            field=models.CharField(help_text='Original name of the uploaded file', max_length=255, verbose_name='Original Filename'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='Previous file that this file replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='files.manuscriptfile', verbose_name='Replaces'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='revision_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Which revision this file belongs to', verbose_name='Revision Number'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Submission this file belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submission', verbose_name='Submission'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='virus_scan_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Virus Scan Date'),
        ),
        migrations.AlterField(
            model_name='manuscriptfile',
            name='virus_scanned',
            field=models.BooleanField(default=False, help_text='Has the file been scanned for viruses?', verbose_name='Virus Scanned'),
        ),
    ]
