# Generated by Django 5.2.10 on 2026-02-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_filedownloadlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptfile',
            name='file_type',
            field=models.CharField(choices=[('main_text', 'Main Text'), ('cover_letter', 'Cover Letter'), ('title_page', 'Title Page'), ('abstract', 'Abstract'), ('tables', 'Tables'), ('figures', 'Figures'), ('supplementary', 'Supplementary Files'), ('ethics_approval', 'Ethics Approval Document'), ('copyright', 'Copyright Form'), ('revision', 'Revision File'), ('revision_notes', 'Revision Notes'), ('system_pdf', 'System Generated PDF'), ('other', 'Other')], db_index=True, default='other', help_text='Type of the file', max_length=30, verbose_name='File Type'),
        ),
    ]
