# Generated by Django 5.2.10 on 2026-03-02 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0004_remove_author_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome'), ('submission_confirmation', 'Submission Confirmation'), ('status_change', 'Status Change'), ('withdrawal_confirmation', 'Withdrawal Confirmation'), ('revision_request', 'Revision Request'), ('decision', 'Decision Notification'), ('other', 'Other')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_confirmation', models.BooleanField(default=True, help_text='Email when manuscript is submitted')),
                ('status_updates', models.BooleanField(default=True, help_text='Email when submission status changes')),
                ('revision_requests', models.BooleanField(default=True, help_text='Email when revision is requested')),
                ('decision_notifications', models.BooleanField(default=True, help_text='Email for editorial decisions')),
                ('system_announcements', models.BooleanField(default=True, help_text='General system announcements')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Preference',
                'verbose_name_plural': 'Email Preferences',
            },
        ),
    ]
