# Generated by Django 5.2.10 on 2026-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_email_log_and_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome"),
                    ("submission_confirmation", "Submission Confirmation"),
                    ("status_change", "Status Change"),
                    ("withdrawal_confirmation", "Withdrawal Confirmation"),
                    ("revision_request", "Revision Request"),
                    ("decision", "Decision Notification"),
                    ("profile_reminder", "Profile Reminder"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
