# Generated by Django 5.2.10 on 2026-01-10 16:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orcid_id', models.CharField(help_text='ORCID tanımlayıcısı (örn: 0000-0002-1825-0097)', max_length=19, unique=True, verbose_name='ORCID ID')),
                ('orcid_access_token', models.TextField(blank=True, help_text='ORCID API erişim tokeni', null=True, verbose_name='ORCID Access Token')),
                ('orcid_refresh_token', models.TextField(blank=True, help_text='ORCID token yenileme tokeni', null=True, verbose_name='ORCID Refresh Token')),
                ('orcid_data', models.JSONField(blank=True, default=dict, help_text="ORCID API'den çekilen tam profil verisi", verbose_name='ORCID Profil Verileri')),
                ('last_orcid_sync', models.DateTimeField(blank=True, help_text='ORCID profili en son ne zaman senkronize edildi', null=True, verbose_name='Son ORCID Senkronizasyonu')),
                ('email', models.EmailField(blank=True, help_text="ORCID'den çekilen email adresi", max_length=254, null=True, verbose_name='Email Adresi')),
                ('full_name', models.CharField(blank=True, help_text="ORCID'den çekilen tam ad", max_length=255, verbose_name='Ad Soyad')),
                ('given_name', models.CharField(blank=True, help_text="ORCID'den çekilen ad", max_length=100, verbose_name='Ad')),
                ('family_name', models.CharField(blank=True, help_text="ORCID'den çekilen soyad", max_length=100, verbose_name='Soyad')),
                ('institution', models.CharField(blank=True, help_text="ORCID'den çekilen kurum bilgisi", max_length=255, verbose_name='Kurum')),
                ('department', models.CharField(blank=True, help_text="ORCID'den çekilen departman bilgisi", max_length=255, verbose_name='Departman')),
                ('is_reviewer', models.BooleanField(default=False, help_text='Kullanıcı hakem olarak görev yapabilir mi?', verbose_name='Hakem mi?')),
                ('is_editor', models.BooleanField(default=False, help_text='Kullanıcı editör olarak görev yapabilir mi?', verbose_name='Editör mü?')),
                ('is_staff', models.BooleanField(default=False, help_text='Kullanıcı admin paneline erişebilir mi?', verbose_name='Personel')),
                ('is_active', models.BooleanField(default=True, help_text='Kullanıcı hesabı aktif mi?', verbose_name='Aktif')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kayıt Tarihi')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Son Giriş')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['orcid_id'], name='users_user_orcid_i_2e0222_idx'), models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx')],
            },
        ),
    ]
