# Generated by Django 5.2.10 on 2026-01-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Posta adresi', verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Kısa biyografi (maks. 1000 karakter)', max_length=1000, verbose_name='Biyografi'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Şehir', max_length=100, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Ülke', max_length=100, verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email adresi doğrulandı mı?', verbose_name='Email Doğrulandı'),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list, help_text='Uzmanlık alanları listesi', verbose_name='Uzmanlık Alanları'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_chief_editor',
            field=models.BooleanField(default=False, help_text='Kullanıcı baş editör mü?', verbose_name='Baş Editör mü?'),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid_token_expires',
            field=models.DateTimeField(blank=True, help_text='ORCID access token ne zaman sona eriyor', null=True, verbose_name='Token Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='İletişim telefon numarası', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Kullanıcı profil bilgilerini doldurdu mu?', verbose_name='Profil Tamamlandı'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewer_interests',
            field=models.JSONField(blank=True, default=list, help_text='Hakemlik yapmak istediği alanlar', verbose_name='Hakemlik İlgi Alanları'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('', 'Seçiniz'), ('prof_dr', 'Prof. Dr.'), ('doc_dr', 'Doç. Dr.'), ('dr_ogr_uyesi', 'Dr. Öğr. Üyesi'), ('dr', 'Dr.'), ('ogr_gor', 'Öğr. Gör.'), ('ars_gor', 'Arş. Gör.'), ('uzman', 'Uzman'), ('ogrenci', 'Öğrenci'), ('diger', 'Diğer')], help_text='Akademik unvan', max_length=50, verbose_name='Unvan'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Kişisel veya kurumsal web sitesi', verbose_name='Web Sitesi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Departman veya bölüm', max_length=255, verbose_name='Departman/Bölüm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='İletişim email adresi', max_length=254, null=True, verbose_name='Email Adresi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=True, help_text='Soyad', max_length=100, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Tam ad', max_length=255, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='given_name',
            field=models.CharField(blank=True, help_text='Ad', max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, help_text='Bağlı olduğu kurum', max_length=255, verbose_name='Kurum'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Kullanıcı hesabı aktif mi?', verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orcid_id',
            field=models.CharField(db_index=True, help_text='ORCID tanımlayıcısı (örn: 0000-0002-1825-0097)', max_length=19, unique=True, verbose_name='ORCID ID'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_reviewer'], name='users_user_is_revi_ceb5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_editor'], name='users_user_is_edit_0aa254_idx'),
        ),
    ]
