# Generated by Django 5.2.10 on 2026-01-11 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_bio_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Mailing address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography (max 1000 characters)', max_length=1000, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department or division', max_length=255, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Contact email address', max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Has the email address been verified?', verbose_name='Email Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list, help_text='List of expertise areas', verbose_name='Expertise Areas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=True, help_text='Last name', max_length=100, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='given_name',
            field=models.CharField(blank=True, help_text='First name', max_length=100, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, help_text='Affiliated institution', max_length=255, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Is the user account active?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_chief_editor',
            field=models.BooleanField(default=False, help_text='Is the user a chief editor?', verbose_name='Is Chief Editor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_editor',
            field=models.BooleanField(default=False, help_text='Can the user serve as an editor?', verbose_name='Is Editor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_reviewer',
            field=models.BooleanField(default=False, help_text='Can the user serve as a reviewer?', verbose_name='Is Reviewer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Can the user access the admin panel?', verbose_name='Staff Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_orcid_sync',
            field=models.DateTimeField(blank=True, help_text='When the ORCID profile was last synchronized', null=True, verbose_name='Last ORCID Sync'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orcid_access_token',
            field=models.TextField(blank=True, help_text='ORCID API access token', null=True, verbose_name='ORCID Access Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orcid_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw profile data from ORCID API', verbose_name='ORCID Profile Data'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orcid_id',
            field=models.CharField(db_index=True, help_text='ORCID identifier (e.g., 0000-0002-1825-0097)', max_length=19, unique=True, verbose_name='ORCID ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orcid_refresh_token',
            field=models.TextField(blank=True, help_text='ORCID token refresh token', null=True, verbose_name='ORCID Refresh Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orcid_token_expires',
            field=models.DateTimeField(blank=True, help_text='When the ORCID access token expires', null=True, verbose_name='Token Expiry'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Has the user completed their profile?', verbose_name='Profile Completed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reviewer_interests',
            field=models.JSONField(blank=True, default=list, help_text='Areas of interest for reviewing', verbose_name='Reviewer Interests'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('prof', 'Professor'), ('assoc_prof', 'Associate Professor'), ('asst_prof', 'Assistant Professor'), ('dr', 'Doctor'), ('lecturer', 'Lecturer'), ('researcher', 'Researcher'), ('phd_student', 'PhD Student'), ('msc_student', 'MSc Student'), ('other', 'Other')], help_text='Academic title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Personal or institutional website', verbose_name='Website'),
        ),
    ]
