# Generated by Django 5.2.10 on 2026-01-11 08:46

import django.core.validators
import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manuscript_id', models.CharField(blank=True, db_index=True, help_text='Otomatik oluşturulan makale numarası (örn: TRU-2026-0001)', max_length=20, null=True, unique=True, verbose_name='Makale Numarası')),
                ('status', django_fsm.FSMField(choices=[('draft', 'Taslak'), ('submitted', 'Gönderildi'), ('under_review', 'İncelemede'), ('revision_required', 'Revizyon Gerekli'), ('revision_submitted', 'Revizyon Gönderildi'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('withdrawn', 'Geri Çekildi'), ('published', 'Yayınlandı')], db_index=True, default='draft', help_text='Makalenin mevcut durumu', max_length=50, protected=True, verbose_name='Durum')),
                ('title', models.CharField(help_text='Makalenin başlığı', max_length=500, verbose_name='Başlık')),
                ('title_en', models.CharField(blank=True, help_text='Makalenin İngilizce başlığı (opsiyonel)', max_length=500, verbose_name='İngilizce Başlık')),
                ('abstract', models.TextField(help_text='Makalenin özeti (maks. 5000 karakter)', max_length=5000, verbose_name='Özet')),
                ('abstract_en', models.TextField(blank=True, help_text='İngilizce özet (opsiyonel)', max_length=5000, verbose_name='İngilizce Özet')),
                ('keywords', models.JSONField(default=list, help_text='Anahtar kelimeler listesi', verbose_name='Anahtar Kelimeler')),
                ('keywords_en', models.JSONField(blank=True, default=list, help_text='İngilizce anahtar kelimeler', verbose_name='İngilizce Anahtar Kelimeler')),
                ('article_type', models.CharField(choices=[('research', 'Araştırma Makalesi'), ('review', 'Derleme'), ('case_report', 'Olgu Sunumu'), ('short_communication', 'Kısa Bildiri'), ('letter', 'Editöre Mektup'), ('editorial', 'Editöryal'), ('other', 'Diğer')], default='research', help_text='Makalenin türü', max_length=30, verbose_name='Makale Türü')),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'İngilizce')], default='tr', help_text='Makalenin yazıldığı dil', max_length=5, verbose_name='Dil')),
                ('cover_letter', models.TextField(blank=True, help_text='Editöre kapak mektubu', verbose_name='Kapak Mektubu')),
                ('ethics_statement', models.TextField(blank=True, help_text='Etik kurul onayı ve beyanı', verbose_name='Etik Beyanı')),
                ('ethics_approval_number', models.CharField(blank=True, help_text='Etik kurul onay numarası (varsa)', max_length=100, verbose_name='Etik Kurul Onay Numarası')),
                ('conflict_of_interest', models.TextField(blank=True, help_text='Çıkar çatışması beyanı', verbose_name='Çıkar Çatışması Beyanı')),
                ('funding_statement', models.TextField(blank=True, help_text='Araştırma finansmanı bilgisi', verbose_name='Finansman Beyanı')),
                ('wizard_step', models.PositiveSmallIntegerField(default=1, help_text="Gönderim wizard'ında şu anki adım (1-6)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Wizard Adımı')),
                ('wizard_data', models.JSONField(blank=True, default=dict, help_text='Wizard adımlarından toplanan geçici veriler', verbose_name='Wizard Verileri')),
                ('revision_number', models.PositiveSmallIntegerField(default=0, help_text='Kaçıncı revizyon', verbose_name='Revizyon Numarası')),
                ('revision_notes', models.TextField(blank=True, help_text='Editör revizyon talep notları', verbose_name='Revizyon Notları')),
                ('revision_deadline', models.DateTimeField(blank=True, help_text='Revizyon teslim tarihi', null=True, verbose_name='Revizyon Son Tarihi')),
                ('editor_notes', models.TextField(blank=True, help_text='Editörün dahili notları', verbose_name='Editör Notları')),
                ('editor_decision', models.CharField(blank=True, choices=[('accept', 'Kabul'), ('minor_revision', 'Küçük Revizyon'), ('major_revision', 'Büyük Revizyon'), ('reject', 'Red')], help_text='Editörün nihai kararı', max_length=50, verbose_name='Editör Kararı')),
                ('editor_decision_date', models.DateTimeField(blank=True, help_text='Editör kararının verildiği tarih', null=True, verbose_name='Karar Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Makalenin ilk gönderildiği tarih', null=True, verbose_name='Gönderim Tarihi')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Makalenin kabul edildiği tarih', null=True, verbose_name='Kabul Tarihi')),
                ('published_at', models.DateTimeField(blank=True, help_text='Makalenin yayınlandığı tarih', null=True, verbose_name='Yayın Tarihi')),
                ('assigned_editor', models.ForeignKey(blank=True, help_text='Makaleyi değerlendiren editör', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Editör')),
                ('submitter', models.ForeignKey(help_text='Makaleyi sisteme gönderen kullanıcı', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Gönderim',
                'verbose_name_plural': 'Gönderimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orcid_id', models.CharField(blank=True, help_text="Yazarın ORCID ID'si", max_length=19, verbose_name='ORCID ID')),
                ('given_name', models.CharField(help_text='Yazarın adı', max_length=100, verbose_name='Ad')),
                ('family_name', models.CharField(help_text='Yazarın soyadı', max_length=100, verbose_name='Soyad')),
                ('email', models.EmailField(help_text='Yazarın email adresi', max_length=254, verbose_name='Email')),
                ('institution', models.CharField(help_text='Yazarın bağlı olduğu kurum', max_length=255, verbose_name='Kurum')),
                ('department', models.CharField(blank=True, help_text='Departman veya bölüm', max_length=255, verbose_name='Departman')),
                ('country', models.CharField(blank=True, help_text='Kurumun bulunduğu ülke', max_length=100, verbose_name='Ülke')),
                ('city', models.CharField(blank=True, help_text='Kurumun bulunduğu şehir', max_length=100, verbose_name='Şehir')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Yazar listesindeki sıra (1 = birinci yazar)', verbose_name='Sıra')),
                ('is_corresponding', models.BooleanField(default=False, help_text='Bu yazar sorumlu (corresponding) yazar mı?', verbose_name='Sorumlu Yazar')),
                ('contribution', models.TextField(blank=True, help_text='Yazarın makaleye katkısı (CRediT taxonomy)', verbose_name='Katkı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.ForeignKey(blank=True, help_text='Sistemde kayıtlı kullanıcı (varsa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorships', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('submission', models.ForeignKey(help_text='Bu yazarın ait olduğu gönderim', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='submissions.submission', verbose_name='Gönderim')),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Gönderildi'), ('under_review', 'İncelemede'), ('revision_required', 'Revizyon Gerekli'), ('revision_submitted', 'Revizyon Gönderildi'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('withdrawn', 'Geri Çekildi'), ('published', 'Yayınlandı')], max_length=30, verbose_name='Önceki Durum')),
                ('to_status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Gönderildi'), ('under_review', 'İncelemede'), ('revision_required', 'Revizyon Gerekli'), ('revision_submitted', 'Revizyon Gönderildi'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('withdrawn', 'Geri Çekildi'), ('published', 'Yayınlandı')], max_length=30, verbose_name='Yeni Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='submissions.submission', verbose_name='Gönderim')),
            ],
            options={
                'verbose_name': 'Durum Geçmişi',
                'verbose_name_plural': 'Durum Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['manuscript_id'], name='submissions_manuscr_45941c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_c2b4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitter'], name='submissions_submitt_1c7cde_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assigned_editor'], name='submissions_assigne_a7156b_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['created_at'], name='submissions_created_d3a853_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='submissions_submitt_f62c88_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['submission', 'order'], name='submissions_submiss_e0710d_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['email'], name='submissions_email_f7114d_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['orcid_id'], name='submissions_orcid_i_a84c89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('submission', 'order')},
        ),
    ]
