# Generated by Django 5.2.10 on 2026-01-11 08:55

import django.core.validators
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['order'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
        migrations.AlterModelOptions(
            name='submissionstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Status History', 'verbose_name_plural': 'Status Histories'},
        ),
        migrations.AlterField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, help_text='City of the institution', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='author',
            name='contribution',
            field=models.TextField(blank=True, help_text="Author's contribution to the manuscript (CRediT taxonomy)", verbose_name='Contribution'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, help_text='Country of the institution', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='author',
            name='department',
            field=models.CharField(blank=True, help_text='Department or division', max_length=255, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(help_text="Author's email address", max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='author',
            name='family_name',
            field=models.CharField(help_text="Author's last name", max_length=100, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='given_name',
            field=models.CharField(help_text="Author's first name", max_length=100, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='institution',
            field=models.CharField(help_text="Author's affiliated institution", max_length=255, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_corresponding',
            field=models.BooleanField(default=False, help_text='Is this the corresponding author?', verbose_name='Corresponding Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='orcid_id',
            field=models.CharField(blank=True, help_text="Author's ORCID ID", max_length=19, verbose_name='ORCID ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Order in the author list (1 = first author)', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='author',
            name='submission',
            field=models.ForeignKey(help_text='Submission this author belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='submissions.submission', verbose_name='Submission'),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Registered user in the system (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=models.TextField(help_text='Abstract of the manuscript (max 5000 characters)', max_length=5000, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='abstract_en',
            field=models.TextField(blank=True, help_text='English abstract (optional)', max_length=5000, verbose_name='English Abstract'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='Date when the manuscript was accepted', null=True, verbose_name='Accepted At'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='article_type',
            field=models.CharField(choices=[('research', 'Research Article'), ('review', 'Review Article'), ('case_report', 'Case Report'), ('short_communication', 'Short Communication'), ('letter', 'Letter to the Editor'), ('editorial', 'Editorial'), ('other', 'Other')], default='research', help_text='Type of the article', max_length=30, verbose_name='Article Type'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assigned_editor',
            field=models.ForeignKey(blank=True, help_text='Editor handling this manuscript', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Editor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='conflict_of_interest',
            field=models.TextField(blank=True, help_text='Conflict of interest declaration', verbose_name='Conflict of Interest Statement'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Cover letter to the editor', verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='editor_decision',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], help_text='Final decision by the editor', max_length=50, verbose_name='Editor Decision'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='editor_decision_date',
            field=models.DateTimeField(blank=True, help_text='Date when the decision was made', null=True, verbose_name='Decision Date'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='editor_notes',
            field=models.TextField(blank=True, help_text='Internal notes from the editor', verbose_name='Editor Notes'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ethics_approval_number',
            field=models.CharField(blank=True, help_text='Ethics committee approval number (if applicable)', max_length=100, verbose_name='Ethics Approval Number'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ethics_statement',
            field=models.TextField(blank=True, help_text='Ethics approval and statement', verbose_name='Ethics Statement'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='funding_statement',
            field=models.TextField(blank=True, help_text='Research funding information', verbose_name='Funding Statement'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.JSONField(default=list, help_text='List of keywords', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords_en',
            field=models.JSONField(blank=True, default=list, help_text='English keywords', verbose_name='English Keywords'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish')], default='en', help_text='Language of the manuscript', max_length=5, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='manuscript_id',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated manuscript number (e.g., TRU-2026-0001)', max_length=20, null=True, unique=True, verbose_name='Manuscript ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Date when the manuscript was published', null=True, verbose_name='Published At'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='revision_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for revision submission', null=True, verbose_name='Revision Deadline'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='revision_notes',
            field=models.TextField(blank=True, help_text='Editor revision request notes', verbose_name='Revision Notes'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='revision_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current revision number', verbose_name='Revision Number'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('revision_submitted', 'Revision Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('published', 'Published')], db_index=True, default='draft', help_text='Current status of the manuscript', max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Date when the manuscript was first submitted', null=True, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(help_text='User who submitted the manuscript', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(help_text='Title of the manuscript', max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title_en',
            field=models.CharField(blank=True, help_text='English title of the manuscript (optional)', max_length=500, verbose_name='English Title'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='wizard_data',
            field=models.JSONField(blank=True, default=dict, help_text='Temporary data collected from wizard steps', verbose_name='Wizard Data'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='wizard_step',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current step in the submission wizard (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Wizard Step'),
        ),
        migrations.AlterField(
            model_name='submissionstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AlterField(
            model_name='submissionstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='submissionstatushistory',
            name='from_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('revision_submitted', 'Revision Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('published', 'Published')], max_length=30, verbose_name='From Status'),
        ),
        migrations.AlterField(
            model_name='submissionstatushistory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='submissionstatushistory',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='submissions.submission', verbose_name='Submission'),
        ),
        migrations.AlterField(
            model_name='submissionstatushistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('revision_submitted', 'Revision Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('published', 'Published')], max_length=30, verbose_name='To Status'),
        ),
    ]
