# Generated by Django 5.2.10 on 2026-03-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_remove_author_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='revision_response',
            field=models.TextField(blank=True, help_text='Author response to reviewer comments', verbose_name='Revision Response'),
        ),
        migrations.AddField(
            model_name='submission',
            name='revision_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the revision was last submitted', null=True, verbose_name='Revision Submitted At'),
        ),
    ]
