# Generated by Django 5.2.10 on 2026-03-11 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_add_revision_response_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Correspondence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("author_to_editor", "Author to Editor"),
                            ("editor_to_author", "Editor to Author"),
                            ("decision_letter", "Decision Letter"),
                            ("system", "System Message"),
                        ],
                        max_length=30,
                        verbose_name="Message Type",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Subject"
                    ),
                ),
                ("body", models.TextField(verbose_name="Body")),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_correspondence",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondence",
                        to="submissions.submission",
                        verbose_name="Submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correspondence",
                "verbose_name_plural": "Correspondence",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["submission", "created_at"],
                        name="submissions_submiss_07cac8_idx",
                    )
                ],
            },
        ),
    ]
